// ============================
// EffiSync Mock Data
// ============================

// ---- Calendar Tasks ----
export const mockTasks = [
  {
    id: '1',
    title: 'Team standup',
    description: 'Daily sync with the dev team',
    date: new Date().toISOString().split('T')[0],
    startTime: '09:00',
    endTime: '09:30',
    color: '#904399',
    done: false,
    isPermanent: false,
  },
  {
    id: '2',
    title: 'Lunch break',
    description: 'Recharge time',
    date: new Date().toISOString().split('T')[0],
    startTime: '12:00',
    endTime: '13:00',
    color: '#5D0E66',
    done: false,
    isPermanent: true,
  },
  {
    id: '3',
    title: 'Design review',
    description: 'Review new dashboard mockups',
    date: new Date().toISOString().split('T')[0],
    startTime: '14:00',
    endTime: '15:30',
    color: '#F9C7FF',
    done: false,
    isPermanent: false,
  },
  {
    id: '4',
    title: 'Gym session',
    description: 'Leg day workout',
    date: (() => { const d = new Date(); d.setDate(d.getDate() + 1); return d.toISOString().split('T')[0]; })(),
    startTime: '18:00',
    endTime: '19:30',
    color: '#904399',
    done: false,
    isPermanent: false,
  },
  {
    id: '5',
    title: 'Project deadline',
    description: 'Submit final deliverables',
    date: (() => { const d = new Date(); d.setDate(d.getDate() + 3); return d.toISOString().split('T')[0]; })(),
    startTime: '16:00',
    endTime: '17:00',
    color: '#5D0E66',
    done: false,
    isPermanent: false,
  },
  {
    id: '6',
    title: 'Morning jog',
    description: 'Run in the park',
    date: (() => { const d = new Date(); d.setDate(d.getDate() + 2); return d.toISOString().split('T')[0]; })(),
    startTime: '07:00',
    endTime: '07:45',
    color: '#904399',
    done: true,
    isPermanent: false,
  },
];

// ---- Permanent Schedules ----
export const mockPermanentSchedules = [
  {
    id: 'p1',
    title: 'Work',
    startTime: '09:00',
    endTime: '17:00',
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    color: '#904399',
  },
  {
    id: 'p2',
    title: 'Lunch',
    startTime: '12:00',
    endTime: '13:00',
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    color: '#5D0E66',
  },
];

// ---- Members (simulated user database) ----
export const mockMembers = [
  {
    id: '1',
    name: 'Alex Popescu',
    role: 'Admin',
    avatar: null,
    busySchedule: [
      { day: 'Monday', start: '09:00', end: '17:00' },
      { day: 'Tuesday', start: '09:00', end: '17:00' },
      { day: 'Wednesday', start: '09:00', end: '17:00' },
      { day: 'Thursday', start: '09:00', end: '17:00' },
      { day: 'Friday', start: '09:00', end: '15:00' },
    ],
  },
  {
    id: '2',
    name: 'Maria Ionescu',
    role: 'Member',
    avatar: null,
    busySchedule: [
      { day: 'Monday', start: '08:00', end: '14:00' },
      { day: 'Wednesday', start: '10:00', end: '16:00' },
      { day: 'Friday', start: '08:00', end: '12:00' },
    ],
  },
  {
    id: '3',
    name: 'Andrei Radu',
    role: 'Member',
    avatar: null,
    busySchedule: [
      { day: 'Monday', start: '10:00', end: '18:00' },
      { day: 'Tuesday', start: '10:00', end: '18:00' },
      { day: 'Wednesday', start: '10:00', end: '18:00' },
      { day: 'Thursday', start: '10:00', end: '18:00' },
      { day: 'Friday', start: '10:00', end: '16:00' },
      { day: 'Saturday', start: '12:00', end: '16:00' },
    ],
  },
  {
    id: '4',
    name: 'Elena Vasile',
    role: 'Lead',
    avatar: null,
    busySchedule: [
      { day: 'Monday', start: '09:00', end: '17:00' },
      { day: 'Tuesday', start: '09:00', end: '17:00' },
      { day: 'Wednesday', start: '09:00', end: '13:00' },
      { day: 'Thursday', start: '09:00', end: '17:00' },
      { day: 'Friday', start: '09:00', end: '14:00' },
    ],
  },
  {
    id: '5',
    name: 'Mihai Dumitrescu',
    role: 'Developer',
    avatar: null,
    busySchedule: [
      { day: 'Monday', start: '08:00', end: '16:00' },
      { day: 'Tuesday', start: '08:00', end: '16:00' },
      { day: 'Wednesday', start: '08:00', end: '16:00' },
      { day: 'Thursday', start: '08:00', end: '16:00' },
      { day: 'Friday', start: '08:00', end: '12:00' },
    ],
  },
  {
    id: '6',
    name: 'Sofia Marin',
    role: 'Designer',
    avatar: null,
    busySchedule: [
      { day: 'Tuesday', start: '10:00', end: '14:00' },
      { day: 'Thursday', start: '10:00', end: '14:00' },
    ],
  },
  {
    id: '7',
    name: 'Cristian Popa',
    role: 'Member',
    avatar: null,
    busySchedule: [
      { day: 'Monday', start: '12:00', end: '18:00' },
      { day: 'Wednesday', start: '12:00', end: '18:00' },
      { day: 'Friday', start: '12:00', end: '18:00' },
    ],
  },
];

// ---- Groups (simulated database) ----
export const mockGroups = [
  {
    id: 'g1',
    name: 'Household',
    type: 'Household',
    description: 'Family task coordination',
    image: null,
    members: ['1', '2', '3'],
  },
  {
    id: 'g2',
    name: 'Work Team',
    type: 'Work Environment',
    description: 'Dev team sprint tasks',
    image: null,
    members: ['1', '4', '5', '6'],
  },
  {
    id: 'g3',
    name: 'Friends',
    type: 'Friend Group',
    description: 'Weekend plans and outings',
    image: null,
    members: ['1', '2', '7'],
  },
];

// ---- Group Tasks ----
export const mockGroupTasks = [
  {
    id: 'gt1',
    title: 'Clean living room',
    description: 'Vacuum and dust the living room',
    priority: 'low',
    points: 5,
    status: 'open',
    assignedTo: null,
    aiSuggested: true,
    aiSuggestedTo: '1',
    aiSuggestedTime: '18:00 - 19:00',
    groupId: 'g1',
    refusalCount: 0,
    date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'gt2',
    title: 'Fix CI pipeline',
    description: 'Debug failing test suite in staging',
    priority: 'high',
    points: 15,
    status: 'in-progress',
    assignedTo: '4',
    aiSuggested: false,
    aiSuggestedTo: null,
    aiSuggestedTime: null,
    groupId: 'g2',
    refusalCount: 0,
    date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'gt3',
    title: 'Buy groceries',
    description: 'Weekly grocery shopping',
    priority: 'medium',
    points: 8,
    status: 'open',
    assignedTo: null,
    aiSuggested: true,
    aiSuggestedTo: '2',
    aiSuggestedTime: '10:00 - 11:30',
    groupId: 'g1',
    refusalCount: 0,
    date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'gt4',
    title: 'Code review PR #42',
    description: 'Review the authentication refactor pull request',
    priority: 'high',
    points: 10,
    status: 'open',
    assignedTo: null,
    aiSuggested: false,
    aiSuggestedTo: null,
    aiSuggestedTime: null,
    groupId: 'g2',
    refusalCount: 0,
    date: (() => { const d = new Date(); d.setDate(d.getDate() + 1); return d.toISOString().split('T')[0]; })(),
  },
  {
    id: 'gt5',
    title: 'Plan weekend trip',
    description: 'Research destinations and book accommodation',
    priority: 'low',
    points: 6,
    status: 'open',
    assignedTo: null,
    aiSuggested: true,
    aiSuggestedTo: '1',
    aiSuggestedTime: '20:00 - 21:00',
    groupId: 'g3',
    refusalCount: 0,
    date: (() => { const d = new Date(); d.setDate(d.getDate() + 2); return d.toISOString().split('T')[0]; })(),
  },
  {
    id: 'gt6',
    title: 'Update design system',
    description: 'Add new color tokens and component variants',
    priority: 'medium',
    points: 12,
    status: 'done',
    assignedTo: '6',
    aiSuggested: false,
    aiSuggestedTo: null,
    aiSuggestedTime: null,
    groupId: 'g2',
    refusalCount: 0,
    date: (() => { const d = new Date(); d.setDate(d.getDate() - 1); return d.toISOString().split('T')[0]; })(),
  },
];

// ---- Subscription Plans ----
export const subscriptionPlans = [
  {
    id: 'single',
    name: 'Single Subscription',
    price: '€4.99',
    period: '/month',
    features: [
      'Personal calendar',
      'Task reminders',
      'Usual schedule setup',
      'Up to 50 tasks/month',
      'Mobile access',
    ],
    featured: false,
  },
  {
    id: 'group',
    name: 'Group',
    price: '€9.99',
    period: '/month',
    features: [
      'Everything in Single',
      'AI schedule suggestions',
      'Group sync (up to 5 groups)',
      'Smart task planning',
      'Priority notifications',
      'Overlap detection',
      'Productivity insights',
    ],
    featured: false,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: '€99.99',
    period: '/month',
    features: [
      'Everything in Group',
      'Unlimited teams',
      'Custom workflows',
      'Advanced group planning',
      'Admin dashboard',
      'API access',
      'Dedicated support',
    ],
    featured: false,
  },
];

// ---- Product Features (for StickyScroll) ----
export const productFeatures = [
  {
    id: 'personal',
    title: 'Personal Calendar',
    subtitle: 'Your day, your way.',
    description: 'Organize your routine, tasks, and reminders with an intuitive calendar designed around your life. Set your usual schedule once and let EffiSync build around it.',
    icon: '📅',
    visual: 'calendar',
  },
  {
    id: 'groups',
    title: 'Smart Groups',
    subtitle: 'Sync with your people.',
    description: "See your team's availability at a glance. Coordinate shared tasks, plan group events, and never double-book again. Everyone stays in the loop.",
    icon: '👥',
    visual: 'groups',
  },
  {
    id: 'ai',
    title: 'AI Assistant',
    subtitle: 'Your schedule, optimized.',
    description: 'EffiSync detects overlaps, overtime, and idle time automatically. Get smart suggestions to redistribute tasks, balance workload, and make every hour count.',
    icon: '🤖',
    visual: 'ai',
  },
  {
    id: 'balance',
    title: 'Better Balance',
    subtitle: 'Work hard. Rest well.',
    description: 'EffiSync protects your sleep, meals, breaks, and deep work time. Because productivity means nothing if you burn out getting there.',
    icon: '⚖️',
    visual: 'balance',
  },
];
